# -*- coding: utf-8 -*-
"""DepthFirstSearch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kVg6RO06DTLVFfQDUCskeMI7IlUGzRLc
"""

def depth_first_search(graph, start, visited):
 visited.add(start)
 print(start)
 for neighbor in graph[start]:
    if neighbor not in visited:
      depth_first_search(graph,neighbor,visited)

graph = {
  'A': ['B', 'G'],
  'B': ['C', 'D', 'E'],
  'C': [],
  'D': [],
  'E': ['F'],
  'F': [],
  'G': ['H'],
  'H': ['I'],
  'I': []
}
visited = set()
depth_first_search(graph,"A",visited)